export type FieldType = "string" | "number" | "boolean" | "date";

export interface FieldSchema {
  name: string;
  type: FieldType;
  required?: boolean;
  format?: string;
}

/**
 * Per-schema header aliases for flexible column matching.
 * Keys are normalized (lowercase, no separators) alternative names.
 * Values are the canonical field names from the schema.
 * Only includes genuinely different names — case/underscore/space
 * variations are handled automatically by the normalization engine.
 */
export const headerAliases: Record<string, Record<string, string>> = {
  "election-results": {
    jurisdiction: "ContestJurisdiction",
    disttype: "DistrictType",
    candidatename: "CandidateNameYN",
    hascandidate: "CandidateNameYN",
    party: "Candidate_Party",
    indbodyname: "IndependentBodyName",
    independentbody: "IndependentBodyName",
    propbudget: "PropBudgetName",
    proposalname: "PropBudgetName",
    desc: "ShortDesc",
    ballotpos: "BallotPosition",
    munireporting: "MunicipalityReporting",
    munitype: "MunicipalityType",
    ed: "ElectionDistrict",
    edcombined: "ElectionDistrictCombined",
    electiondayvotes: "VotesElectionDayAtPollSite",
    edvotes: "VotesElectionDayAtPollSite",
    earlyvotepollsite: "VotesEarlyVoteatPollSite",
    earlyvotemail: "VotesEarlyVotebyMail",
    absentee: "VotesAbesentee",
    absenteevotes: "VotesAbesentee",
    domesticmilitary: "VotesDomesticMilitary",
    overseasmilitary: "VotesOverseasMilitary",
    federalvotes: "VotesFederal",
    uocava: "VotesUOCAVA",
    othervotes: "VotesOther",
    affidavitvotes: "VotesAffidavit",
    blankvoid: "BlankVoidScattered",
    scattered: "BlankVoidScattered",
    rankround: "NYCRankRound",
    transfervotes: "NYCTransferVotes",
    total: "VoteTotal",
    totalvotes: "VoteTotal",
    result: "Outcome",
    winner: "Outcome",
    elecname: "Election_Name",
    pct: "Precinct",
  },
  elections: {
    authname: "Authority_Name",
    authtype: "Authority_Type",
    region: "RegionAssociation",
    user: "UserReporting",
    reporter: "UserReporting",
    fname: "FirstName",
    lname: "LastName",
    phone: "ContactPhone",
    tel: "ContactPhone",
    telephone: "ContactPhone",
    elecdate: "ElectionDate",
    date: "ElectionDate",
    electype: "Election_Type",
    elecname: "Election_Name",
  },
  "voter-history": {
    elecname: "Election_Name",
    muni: "Municipality",
    town: "Municipality",
    munitype: "MunicipalityType",
    lname: "LastName",
    fname: "FirstName",
    mname: "MiddleName",
    mi: "MiddleName",
    middleinitial: "MiddleName",
    suffix: "NameSuffix",
    sex: "Gender",
    party: "PoliticalParty",
    regdate: "RegistrationDate",
    homeaddr: "ResAddr1",
    homeaddress: "ResAddr1",
    homeaddr2: "ResAddr2",
    homecity: "ResCity",
    homestate: "ResState",
    homezip: "ResZip",
    mailaddr: "MailingAddr1",
    mailaddress: "MailingAddr1",
    mailaddr2: "MailingAddr2",
    mailcity: "MailingCity",
    mailstate: "MailingState",
    mailzip: "MailingZip",
    mailcountry: "MailingCountry",
    pct: "Precinct",
    ed: "ElectionDistrict",
    votemethod: "VotingMethod",
    method: "VotingMethod",
    regsource: "RegistrationSource",
    absenteereason: "InvalidAbsenteeBallotReason",
    affidavitreason: "InvalidAffidavitBallotReason",
  },
  "poll-sites": {
    elecname: "Election_Name",
    muni: "Municipality",
    town: "Municipality",
    pct: "Precinct",
    ed: "ElectionDistrict",
    houseno: "HASNO",
    housenumber: "HASNO",
    streetno: "HASNO",
    pollsite: "PollSiteName",
    sitename: "PollSiteName",
    psaddress: "PS_Addr1",
    pollsiteaddr: "PS_Addr1",
    pollsiteaddress: "PS_Addr1",
    psaddress2: "PS_Addr2",
    pscity: "PS_City",
    psstate: "PS_State",
    pszip: "PS_Zip",
    psdesignation: "PS_Desg",
    designation: "PS_Desg",
    desg: "PS_Desg",
  },
};

export const fileSchemas: Record<string, FieldSchema[]> = {
  "election-results": [
    { name: "Election_Name", type: "string", required: true },
    { name: "ContestJurisdiction", type: "string", required: true },
    { name: "ContestType", type: "string", required: true },
    { name: "Office", type: "string", required: false },
    { name: "DistrictType", type: "string", required: true },
    { name: "District", type: "string", required: false },
    { name: "Ward", type: "string", required: false },
    { name: "Precinct", type: "string", required: false },
    { name: "CandidateNameYN", type: "string", required: false },
    { name: "Candidate_Party", type: "string", required: false },
    { name: "IndependentBodyName", type: "string", required: false },
    { name: "PropBudgetName", type: "string", required: false },
    { name: "ShortDesc", type: "string", required: false },
    { name: "BallotPosition", type: "number", required: false },
    { name: "VoteType", type: "string", required: false },
    { name: "VoteFor", type: "number", required: false },
    { name: "MunicipalityReporting", type: "string", required: false },
    { name: "MunicipalityType", type: "string", required: false },
    { name: "ElectionDistrict", type: "string", required: false },
    { name: "ElectionDistrictCombined", type: "string", required: false },
    { name: "VotesElectionDayAtPollSite", type: "number", required: false },
    { name: "VotesEarlyVoteatPollSite", type: "number", required: false },
    { name: "VotesEarlyVotebyMail", type: "number", required: false },
    { name: "VotesAbesentee", type: "number", required: false },
    { name: "VotesDomesticMilitary", type: "number", required: false },
    { name: "VotesOverseasMilitary", type: "number", required: false },
    { name: "VotesFederal", type: "number", required: false },
    { name: "VotesUOCAVA", type: "number", required: false },
    { name: "VotesOther", type: "number", required: false },
    { name: "VotesAffidavit", type: "number", required: false },
    { name: "IAF_NotRegistered", type: "number", required: false },
    { name: "IAF_MovedwithinState", type: "number", required: false },
    { name: "IAF_WrongPollingPlace", type: "number", required: false },
    { name: "IAF_SignatureIssue", type: "number", required: false },
    { name: "IAF_AlreadyVoted", type: "number", required: false },
    { name: "IAF_PrevAbsenteeEarlyVote", type: "number", required: false },
    { name: "IAF_IncompleteAffidavit", type: "number", required: false },
    { name: "IAF_PartyEnrollmentIssue", type: "number", required: false },
    { name: "VotesInvalidAffidavit", type: "number", required: false },
    { name: "BlankVoidScattered", type: "number", required: false },
    { name: "NYCRankRound", type: "number", required: false },
    { name: "NYCTransferVotes", type: "number", required: false },
    { name: "VoteTotal", type: "number", required: true },
    { name: "Outcome", type: "string", required: true },    
  ],
  elections: [
    { name: "Authority_Name", type: "string", required: true },
    { name: "Authority_Type", type: "string", required: true },
    { name: "RegionAssociation", type: "string", required: false },
    { name: "County", type: "string", required: false },
    { name: "UserReporting", type: "string", required: true },
    { name: "FirstName", type: "string", required: true },
    { name: "LastName", type: "string", required: false },
    { name: "Title", type: "string", required: false },
    { name: "ContactPhone", type: "string", required: false },
    { name: "ElectionDate", type: "date", required: true, format: "mm/dd/yyyy" },
    { name: "Election_Type", type: "string", required: true },
    { name: "Election_Name", type: "string", required: true },
    { name: "Amended", type: "string", required: false },
  ],
  "voter-history": [
    { name: "Election_Name", type: "string", required: true },
    { name: "Municipality", type: "string", required: true },
    { name: "MunicipalityType", type: "string", required: true },
    { name: "LastName", type: "string", required: true },
    { name: "FirstName", type: "string", required: true },
    { name: "MiddleName", type: "string", required: false },
    { name: "NameSuffix", type: "string", required: false },
    { name: "Gender", type: "string", required: false },
    { name: "DOB", type: "date", required: false, format: "mm/dd/yyyy" },
    { name: "PoliticalParty", type: "string", required: false },
    { name: "OtherParty", type: "string", required: false },
    { name: "RegistrationDate", type: "date", required: false, format: "mm/dd/yyyy" },
    { name: "ResAddr1", type: "string", required: true },
    { name: "ResAddr2", type: "string", required: false },
    { name: "ResCity", type: "string", required: true },
    { name: "ResState", type: "string", required: true },
    { name: "ResZip", type: "string", required: true },
    { name: "MailingAddr1", type: "string", required: false },
    { name: "MailingAddr2", type: "string", required: false },
    { name: "MailingCity", type: "string", required: false },
    { name: "MailingState", type: "string", required: false },
    { name: "MailingZip", type: "string", required: false },
    { name: "MailingCountry", type: "string", required: false },
    { name: "Ward", type: "string", required: false },
    { name: "Precinct", type: "string", required: false },
    { name: "LD", type: "string", required: false },
    { name: "AD", type: "string", required: false },
    { name: "SD", type: "string", required: false },
    { name: "CD", type: "string", required: false },
    { name: "ElectionDistrict", type: "string", required: false },
    { name: "VotingMethod", type: "string", required: true },
    { name: "Status", type: "string", required: false },
    { name: "Status_Reason", type: "string", required: false },
    { name: "RegistrationSource", type: "string", required: false },
    { name: "InvalidAbsenteeBallotReason", type: "string", required: false },
    { name: "InvalidAffidavitBallotReason", type: "string", required: false },
  ],
  "poll-sites": [
    { name: "Election_Name", type: "string", required: true },
    { name: "Municipality", type: "string", required: true },
    { name: "Ward", type: "string", required: false },
    { name: "Precinct", type: "string", required: false },
    { name: "ElectionDistrict", type: "string", required: true },
    { name: "HASNO", type: "string", required: false },
    { name: "PollSiteName", type: "string", required: true },
    { name: "PS_Addr1", type: "string", required: true },
    { name: "PS_Addr2", type: "string", required: false },
    { name: "PS_City", type: "string", required: true },
    { name: "PS_State", type: "string", required: true },
    { name: "PS_Zip", type: "string", required: true },
    { name: "PS_Desg", type: "string", required: true },
  ],
};